# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'childprevent-website'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['childpreventwebsite:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox:9115'

  - job_name: 'synthetic-monitoring'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'https://your-app/login'
          - 'https://your-app/checkout'
