# docker-compose.observability.yml
version: '3.8'
services:
  # Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.42
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug

  # Log Aggregation
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    depends_on:
      - loki

  # Metrics & Visualization
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - jaeger

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
